<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BNIRTNQ" failures="1" tests="4" name="Test" time="50.807" errors="0" timestamp="2022-10-09T08:26:24 IST">
  <testcase classname="com.SauceDemo.TestClass.TC01_VerifyLoginFunctionality" name="verifyLoginFunctionality" time="1.22"/>
  <testcase classname="com.SauceDemo.TestClass.TC02_VerifyLogOutFunctionality" name="verifyLOgOutFunctionality" time="1.785"/>
  <testcase classname="com.SauceDemo.TestClass.TC03_VerifyBagProductFunctionality" name="verifyBagProductFunctionality" time="1.779"/>
  <testcase classname="com.SauceDemo.TestClass.TC04_VerifyAllProductFunctionality" name="verifyAllProductFunctionality" time="2.377">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.SauceDemo.TestClass.TC04_VerifyAllProductFunctionality.verifyAllProductFunctionality(TC04_VerifyAllProductFunctionality.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllProductFunctionality -->
</testsuite> <!-- Test -->
